;============================================================
;  NuraShade Skin
;  Copyright (c) 2025 NuraShade
;
;  Licensed under the Creative Commons Attribution-ShareAlike 3.0 Unported License.
;  You are free to:
;    • Share — copy and redistribute the material in any medium or format
;    • Adapt — remix, transform, and build upon the material
;      for any purpose, even commercially.
;
;  Under the following terms:
;    • Attribution — You must give appropriate credit, provide a link to the license,
;      and indicate if changes were made.
;    • ShareAlike — If you remix, transform, or build upon the material,
;      you must distribute your contributions under the same license as the original.
;
;  License Details: https://creativecommons.org/licenses/by-sa/3.0/
;============================================================

[Variables]
Background_Width=500
Background_Height=180
Background_Color=32, 32, 32
Background_Opacity=166
Background_Corner_Round=12
Font_Color=255, 255, 255
Font_Face=SF Pro Display
Font_Weight=300
; NightLight Shape Colors
NightLight_Off_Color=200,200,200
NightLight_Off_Opacity=10
NightLight_Off_Hover_Opacity=30
NightLight_On_Color=255,140,0
NightLight_On_Opacity=40
NightLight_On_Hover_Opacity=60
; Brightness Slider
Slider_Width=330
Slider_Height=6
Slider_X=70
Slider_Track_Color=64,64,64
Slider_Fill_Color=255,212,71
Slider_Thumb_Size=20
